= aerospace-workspace(1)
include::util/man-attributes.adoc[]
:manname: aerospace-workspace
// tag::purpose[]
:manpurpose: Focus the specified workspace
// end::purpose[]

// =========================================================== Synopsis
== Synopsis
[verse]
// tag::synopsis[]
aerospace workspace [-h|--help] [--auto-back-and-forth] [--fail-if-noop] <workspace-name>
aerospace workspace [-h|--help] [--wrap-around] [--stdin|--no-stdin] (next|prev|up|down)

// end::synopsis[]

// =========================================================== Description
== Description

// tag::body[]
*1. <workspace-name> syntax*

{manpurpose}

*2. (next|prev|up|down) syntax*

Focuses workspace in *the list* relative to the currently focused workspace.
`next` and `down` focus the next workspace in *the list*.
`prev` and `up` focus the previous workspace in *the list*.

* If `--stdin` is specified, then *the list* is taken from stdin
* Otherwise, *the list* is defined as all workspaces on focused monitor in alphabetical order

// =========================================================== Options
include::util/conditional-options-header.adoc[]

-h, --help:: Print help
--wrap-around:: Make it possible to jump between first and last workspaces using `(next|prev|up|down)`

--auto-back-and-forth::
Automatic `back-and-forth` when switching to already focused workspace.
Incompatible with `--fail-if-noop`

--fail-if-noop::
Exit with non-zero exit code if switch to the already focused workspace.
Incompatible with `--auto-back-and-forth`

--stdin::
Read the list of workspaces from stdin.
Incompatible with `--no-stdin`

--no-stdin::
Ignore the list of workspaces from stdin, even if provided.
Incompatible with `--stdin`

// =========================================================== Examples
include::util/conditional-examples-header.adoc[]

* Go to the next non empty workspace on the focused monitor: +
`aerospace list-workspaces --monitor focused --empty no | aerospace workspace next`
* Go to the previous workspace in the same list using the `up` alias: +
`aerospace workspace up`

// end::body[]

// =========================================================== Footer
include::util/man-footer.adoc[]
